### PR TITLE
Closure bug fixed.

### LINKED ISSUE #15: Fracture closure
Fracture closure in the case of re-meshing and/or the presence of fluid compressibility seems to have a bug.

- [x] #22

### PR DESCRIPTION
**Pull request by Skonki**
This merge fixes the bug of closure. It was an easy fix, with only one file change.

closes #15

### CODE REVIEW

**Review by pedrolimasi — APPROVED** [review]
Nice. Good catch, Andreas!

**Comment by Skonki** [comment]
I will check asap. let you know about the outcome.

**Comment by Skonki** [comment]
Okay, for the monolithic system, we have different issues arising...will not be a quick fix, I fear.  The code does not even run... give me some time...

**Comment by pedrolimasi** [comment]
If the code is unused and solution is complex, I suggest a first one-line commit with something to the effect of

```python
assert isZero(LeakOff), "Message quickly explaining the issue"
```

before going into the bigger rewrite

**Comment by Skonki** [comment]
I have trouble to understand your last comment^^

Did you test everything on  Monolithic as well? Because the issues are fundamental not related to closer or active cells at all....

**Comment by pedrolimasi** [comment]
I suggest the `assert` as a project management tool.

First, it's supposed to document what missing functionality you're fixing with your subsequent commits. It'll be immediately erased by your actual fix, but in case you introduce another bug, the git history will show at-a-glance what you were fixing.

Secondarily, if you need to leave this bug to fix later, the `assert` leaves a trace of the missing functionality pending a fix.

---

I have not tested any example with monolithic system and leak-off. It just occurred to me while reviewing your PR.

**Comment by Skonki** [comment]
Okay I see,

I would go even further, I guess you have not tested any simulation with the monolithic solve which is NOT volume controlled? Because they all fail ;) (i tested radial_MtoK and Experiment_Wu_et_al). There is something missing in the implementation early on and if you fix it you get immediately a singular matrix.

Can you confirm this to me?

**Pull request merged**
